## Propriétés communes (fallback) servies si un service n'a pas de fichier dédié
## Endpoint exemple: http://localhost:8888/<application>/<profile>

# Eureka par défaut (si les clients l'importent)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
