spring.application.name=prescription-Service
spring.datasource.url=jdbc:mysql://localhost:3306/prescription-Service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8086
#eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
# Keycloak / JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/kidneyCare-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/kidneyCare-realm/protocol/openid-connect/certs
# Keycloak Admin (pour inscription patient)
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=kidneyCare-realm
keycloak.admin.username=admin
keycloak.admin.password=admin